### ISSUE TITLE
Workarounds to accommodate existing vaccination. 

### ISSUE THREAD

**Issue by spockoyno** [mrc-ide/nimue#45]
Hi 
I'm interested in using nimue to model introduction of a new vaccine to a country with existing vaccination or changing the supply of an existing vaccine. AFAIK this is not yet possible with the software. 

 I'm wondering if there any workarounds to accommodate this. Eg, might it be possible to create a "synthetic" country 
with parameters approximating existing vaccination, and then simulate from day one for the new vaccine? Or perhaps there is something else.  

Thank you in advance.

**Comment by OJWatson** [comment]
Hey there @spockoyno , 

You can set the population initial conditon with `init`:

```# create our inital conditions
init <- nimue:::init(squire::get_population("Iran")$n, seeding_cases = 5)

# our susceptibles
S_0 <- init$S_0

# let's say 90% already vaccinated in over 15s
prop <- 0.9

# so first what proportion of the over 15s are vaccinated
# let's then distribute vaccines equally over the vaccinated class
S_0[-(1:3),4] <- round(S_0[-(1:3),1] * prop)

# and remember to decrease the number in the unvaccinated susceptible class
S_0[-(1:3),1] <- S_0[-(1:3),1] - S_0[-(1:3),4]

# and update the init
init$S_0 <- S_0

# now see what that impact is if we assume vaccines confer long protection (5000 days)
r <- nimue::run("Iran", init = init, R0 = 3, dur_V = 5000)
plot(r, "deaths")
```

![image](https://user-images.githubusercontent.com/15249565/119480927-0ee43b00-bd4a-11eb-83ad-61522a5c90c3.png)

```
# wheras without that init
r2 <- nimue::run("Iran", R0 = 3, dur_V = 5000)
plot(r2, "deaths")
```

![image](https://user-images.githubusercontent.com/15249565/119480971-19063980-bd4a-11eb-9f37-ce37fe8709e3.png)


Unfortunately, nimue considers all individuals vaccinated to be in one compartment, so changing vaccines over time can only be approximated by changing the vaccine efficacy over time (see documentation for params `vaccine_efficacy_disease` etc to see how to do this).

**Comment by spockoyno** [comment]
Hi @OJWatson. 
Thank you for the explanation & example -- this is super helpful.
